pub const V0_1_REQUIRED_OPERATIONS: [&str; 50] = [
    "profile.list",
    "profile.show",
    "profile.add",
    "profile.update",
    "profile.use",
    "profile.remove",
    "auth.login",
    "auth.status",
    "auth.check",
    "auth.token",
    "auth.logout",
    "entity.get",
    "entity.get-many",
    "entity.by-crosswalk",
    "entity.search",
    "entity.scan",
    "entity.create",
    "entity.upsert",
    "entity.update",
    "entity.delete",
    "entity.history",
    "entity.matches",
    "relation.get",
    "relation.search",
    "relation.scan",
    "relation.create",
    "relation.update",
    "relation.delete",
    "config.get",
    "config.pull",
    "config.validate",
    "config.diff",
    "config.apply",
    "config.backup",
    "task.get",
    "task.list",
    "task.wait",
    "task.cancel",
    "api.request",
    "api.practices.list",
    "api.practices.show",
    "api.practices.check",
    "skills.list",
    "skills.get",
    "skills.path",
    "agent.guide",
    "command.schema",
    "completion.generate",
    "completion.install",
    "doctor",
];

pub const V0_1_REQUIRED_CAPABILITIES: [&str; 1] = ["auth.provider.authorization-code"];

pub const V0_1_OPERATION_SAFETY: [(&str, &str); 50] = [
    ("profile.list", "read"),
    ("profile.show", "read"),
    ("profile.add", "local_write"),
    ("profile.update", "local_write"),
    ("profile.use", "local_write"),
    ("profile.remove", "local_write"),
    ("auth.login", "authentication"),
    ("auth.status", "read"),
    ("auth.check", "read"),
    ("auth.token", "secret_disclosure"),
    ("auth.logout", "local_write"),
    ("entity.get", "read"),
    ("entity.get-many", "read"),
    ("entity.by-crosswalk", "read"),
    ("entity.search", "read"),
    ("entity.scan", "read"),
    ("entity.create", "remote_write"),
    ("entity.upsert", "remote_write"),
    ("entity.update", "remote_write"),
    ("entity.delete", "remote_high_impact"),
    ("entity.history", "read"),
    ("entity.matches", "read"),
    ("relation.get", "read"),
    ("relation.search", "read"),
    ("relation.scan", "read"),
    ("relation.create", "remote_write"),
    ("relation.update", "remote_write"),
    ("relation.delete", "remote_high_impact"),
    ("config.get", "read"),
    ("config.pull", "read"),
    ("config.validate", "read"),
    ("config.diff", "read"),
    ("config.apply", "remote_high_impact"),
    ("config.backup", "read"),
    ("task.get", "read"),
    ("task.list", "read"),
    ("task.wait", "read"),
    ("task.cancel", "remote_high_impact"),
    ("api.request", "dynamic"),
    ("api.practices.list", "read"),
    ("api.practices.show", "read"),
    ("api.practices.check", "read"),
    ("skills.list", "read"),
    ("skills.get", "read"),
    ("skills.path", "read"),
    ("agent.guide", "read"),
    ("command.schema", "read"),
    ("completion.generate", "read"),
    ("completion.install", "local_write"),
    ("doctor", "read"),
];

pub const V0_1_WRITE_OPERATIONS: [&str; 5] = [
    "entity.create",
    "entity.upsert",
    "entity.update",
    "relation.create",
    "relation.update",
];

pub const V0_1_DYNAMIC_MUTATION_ADAPTERS: [&str; 1] = ["api.request"];

pub const V0_1_HIGH_IMPACT_OPERATIONS: [&str; 4] = [
    "entity.delete",
    "relation.delete",
    "config.apply",
    "task.cancel",
];

pub const V0_1_ENDPOINT_REQUIREMENTS: [(&str, &str); 31] = [
    ("auth.login", "typed_primary"),
    ("auth.check", "workflow_component"),
    ("auth.token", "auth_dependency"),
    ("entity.get", "typed_primary"),
    ("entity.get-many", "typed_primary"),
    ("entity.by-crosswalk", "typed_primary"),
    ("entity.search", "typed_primary"),
    ("entity.scan", "typed_primary"),
    ("entity.create", "typed_primary"),
    ("entity.upsert", "typed_primary"),
    ("entity.update", "typed_primary"),
    ("entity.delete", "typed_primary"),
    ("entity.history", "typed_primary"),
    ("entity.matches", "typed_primary"),
    ("relation.get", "typed_primary"),
    ("relation.search", "typed_primary"),
    ("relation.scan", "typed_primary"),
    ("relation.create", "typed_primary"),
    ("relation.update", "typed_primary"),
    ("relation.delete", "typed_primary"),
    ("config.get", "typed_primary"),
    ("config.pull", "typed_primary"),
    ("config.validate", "typed_primary"),
    ("config.diff", "typed_primary"),
    ("config.apply", "typed_primary"),
    ("config.backup", "typed_primary"),
    ("task.get", "typed_primary"),
    ("task.list", "typed_primary"),
    ("task.wait", "typed_primary"),
    ("task.cancel", "typed_primary"),
    ("doctor", "healthcheck_dependency"),
];

pub const REVIEWED_ENDPOINT_BINDINGS: [(&str, &str); 10] = [
    ("auth.login", "auth.client_credentials"),
    ("auth.check", "entity.search"),
    ("auth.token", "auth.client_credentials"),
    ("entity.get", "entity.get"),
    ("entity.by-crosswalk", "entity.by-crosswalk"),
    ("entity.search", "entity.search"),
    ("entity.scan", "entity.scan"),
    ("entity.history", "entity.history"),
    ("entity.matches", "entity.matches"),
    ("doctor", "entity.search"),
];

pub const MVP_ACCEPTANCE_SCENARIOS: [&str; 19] = [
    "MVP-ACCEPT-001",
    "MVP-ACCEPT-002",
    "MVP-ACCEPT-003",
    "MVP-ACCEPT-004",
    "MVP-ACCEPT-005",
    "MVP-ACCEPT-006",
    "MVP-ACCEPT-007",
    "MVP-ACCEPT-008",
    "MVP-ACCEPT-009",
    "MVP-ACCEPT-010",
    "MVP-ACCEPT-011",
    "MVP-ACCEPT-012",
    "MVP-ACCEPT-013",
    "MVP-ACCEPT-014",
    "MVP-ACCEPT-015",
    "MVP-ACCEPT-016",
    "MVP-ACCEPT-017",
    "MVP-ACCEPT-018",
    "MVP-ACCEPT-019",
];

pub const MUTATION_AUDIT_FIELDS: [&str; 16] = [
    "operation_id",
    "request_ids",
    "command",
    "cli_version",
    "profile",
    "environment",
    "tenant",
    "service",
    "principal",
    "input_sha256",
    "affected_resources",
    "started_at",
    "ended_at",
    "result",
    "backup_reference",
    "task_reference",
];

pub const MUTATION_AUDIT_RESULTS: [&str; 7] = [
    "not_sent",
    "failed",
    "partial",
    "accepted",
    "succeeded",
    "canceled",
    "completion_unknown",
];
